ConsistecWettbewerbconnect@htw2013: StringsUndTools Class Reference
StringsUndTools Class Reference
Klasse mit Strings und global benoetigten Funktionen.
#include <StringsUndTools.h>
Static Public Member Functions
static bool istLeer (ifstream &datei)
Funktion die prueft, ob eine Datei leer ist.
static bool dateienGleich (const char *lhs, const char *rhs)
Funktion prueft, ob zwei Dateien den gleichen inhalt haben.
static string helpMenuEncoderDecoder ()
Baut einen String Stream der die Hilfe fuer das Programm encoderDecoder beinhaltet.
Static Public Attributes
static const char * HELP_MENU_ENCODER = "Aufruf: encoder [EINGABEDATEI] [AUSGABEDATEI]\n"
HelpMenu-String fuer Encoder.
static const char * HELP_MENU_ENCODER_TEST = "Aufruf: encoderTest [EINGABEDATEI] [AUSGABEDATEI] [VERGLEICHSDATEI]\n"
HelpMenu-String fuer EncoderTest.
static const char * HELP_MENU_DECODER = "Aufruf: decoder [EINGABEDATEI] [AUSGABEDATEI]\n"
HelpMenu-String fuer Decoder.
static const char * MSG_KEINE_DATEI_GEFUNDEN = "\nKonnte Datei nicht finden oder oeffnen: "
String fuer Exception, dass keine Datei vorhanden ist.
static const char * MSG_DATEI_LEER = "\nDie Eingabedatei ist leer: "
String fuer Exception, dass Datei leer ist.
static const char * PARAM_ENTSCHLUESSELN = "--entschluessen"
langer String fuer Kommandozeilen Parameter bei Entschluesseln
static const char * PARAM_ENTSCHLUESSELN_S = "-e"
kurzer String fuer Kommandozeilen Parameter bei Entschluesseln
static const char * PARAM_VERSCHLUESSELN = "--verschluessen"
langer String fuer Kommandozeilen Parameter bei Verschluesseln
static const char * PARAM_VERSCHLUESSELN_S = "-v"
kurzer String fuer Kommandozeilen Parameter bei Verschluesseln
static const char * PARAM_HELP = "--help"
langer String fuer Kommandozeilen Parameter bei Help
static const char * PARAM_HELP_S = "-h"
kurzer String fuer Kommandozeilen Parameter bei Help
static const char * MSG_VERSCHLUESSELUNG_TRUE = "\nDas neu verschluesselte File entspricht der Referenzdatei, Verschluesselung erfolgreich\n"
String fuer eine erfolgreiche Verschluesselung in encoderTest.
static const char * MSG_VERSCHLUESSELUNG_FALSE = "\nDas neu verschluesselte File entspricht nicht der Referenzdatei, Verschluesselung nicht erfolgreich\n"
String fuer eine nicht erfolgreiche Verschluesselung in encoderTest.
Detailed Description
Klasse mit Strings und global benoetigten Funktionen.
Definition at line 25 of file StringsUndTools.h.
Member Function Documentation
bool StringsUndTools::dateienGleich (const char * lhs, const char * rhs) static
Funktion prueft, ob zwei Dateien den gleichen inhalt haben.
Parameters
lhs Erste Datei des Vergleichs
rhs Zweite Datei des Vergleichs
Returns
Status der Gleichheit
Definition at line 41 of file StringsUndTools.cpp.
Referenced by main().
string StringsUndTools::helpMenuEncoderDecoder () static
Baut einen String Stream der die Hilfe fuer das Programm encoderDecoder beinhaltet.
Returns
o.str() String-Stream der Hilfe
Definition at line 52 of file StringsUndTools.cpp.
Referenced by main().
bool StringsUndTools::istLeer (ifstream & datei) static
Funktion die prueft, ob eine Datei leer ist.
Parameters
datei
Returns
Datei leer oder nicht
Definition at line 36 of file StringsUndTools.cpp.
Referenced by Entschluesseln::Entschluesseln(), and Verschluesseln::Verschluesseln().
The documentation for this class was generated from the following files:
module/StringsUndTools.h
module/StringsUndTools.cpp